spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      # 上述获取的的API-KEY
      api-key: sk-4abb11683db24cf0a163cd1f5c22f41c
      # 使用DeepSeek
      base-url: https://api.deepseek.com
      chat:
        options:
          # 使用的模型
          model: deepseek-chat
          # 采样的随机性 0~1 较高的值将使输出更具随机性，而较低的值将使结果更加集中和确定
          temperature: 0.8
          
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug